title: Carbone
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: person.tchube
      - entity: sun.sun
    cards:
      - type: weather-forecast
        entity: weather.carbone