version: "2.1"
services:
  syncthing:
    image: linuxserver/syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=022
    volumes:
      - type: bind
        source: /cocooning-master/syncthing
        target: /config
      - type: bind
        source: /cocooning-master/hassio
        target: /cocooning-save/hassio
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
