version: "3.2"

services:
  cloud9:
    image: linuxserver/cloud9
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - type: bind
        source: /apps
        target: /code
    ports:
      - 8080:8000
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
networks:
  cocooning-network:
    external: true


